{
 "title": "Energy Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "RACKA4",
    "query": {
     "query": "label_values(masterName{masterName=~\".*RACKA4\"},instance)"
    }
   },
   {
    "name": "RACKA5",
    "query": {
     "query": "label_values(masterName{masterName=~\".*RACKA5\"},instance)"
    }
   },
   {
    "name": "Rack",
    "query": {
     "query": "label_values(masterName,masterName)"
    }
   },
   {
    "name": "RackEndpoint",
    "query": {
     "query": "label_values(masterName{masterName=~\".*$Rack\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "sum(masterPhaseOnePower{instance=~\"$RackEndpoint\"})",
     "legendFormat": "L1"
    },
    {
     "expr": "sum(masterPhaseTwoPower{instance=~\"$RackEndpoint\"})",
     "legendFormat": "L2"
    },
    {
     "expr": "sum(masterPhaseThreePower{instance=~\"$RackEndpoint\"})",
     "legendFormat": "L3"
    }
   ]
  },
  {
   "title": "Active Power",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "masterPhaseOnePower{instance=~\"$RackEndpoint\"}",
     "legendFormat": "L1"
    },
    {
     "expr": "masterPhaseTwoPower{instance=~\"$RackEndpoint\"}",
     "legendFormat": "L2"
    },
    {
     "expr": "masterPhaseThreePower{instance=~\"$RackEndpoint\"}",
     "legendFormat": "L3"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum(increase(masterPhaseOneEnergy{instance=~\"$RackEndpoint\"}[$__range]))",
     "legendFormat": "L1"
    },
    {
     "expr": "sum(increase(masterPhaseTwoEnergy{instance=~\"$RackEndpoint\"}[$__range]))",
     "legendFormat": "L2"
    },
    {
     "expr": "sum(increase(masterPhaseThreeEnergy{instance=~\"$RackEndpoint\"}[$__range]))",
     "legendFormat": "L3"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(masterPhaseOneEnergy{instance=~\"$RackEndpoint\"}[$__range])",
     "legendFormat": "L1"
    },
    {
     "expr": "increase(masterPhaseTwoEnergy{instance=~\"$RackEndpoint\"}[$__range])",
     "legendFormat": "L2"
    },
    {
     "expr": "increase(masterPhaseThreeEnergy{instance=~\"$RackEndpoint\"}[$__range])",
     "legendFormat": "L3"
    }
   ]
  },
  {
   "title": "Energy Total",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "masterPhaseOneEnergy{instance=~\"$RackEndpoint\"}",
     "legendFormat": "L1"
    },
    {
     "expr": "masterPhaseTwoEnergy{instance=~\"$RackEndpoint\"}",
     "legendFormat": "L2"
    },
    {
     "expr": "masterPhaseThreeEnergy{instance=~\"$RackEndpoint\"}",
     "legendFormat": "L3"
    }
   ]
  },
  {
   "title": "Intake Air Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "masterSensorTemperatureOne{instance=~\"$RackEndpoint\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Intake Air Humidity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "masterSensorHumidityOne{instance=~\"$RackEndpoint\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exhaust Air Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "masterSensorTemperatureTwo{instance=~\"$RackEndpoint\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exhaust Air Humidity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "masterSensorHumidityTwo{instance=~\"$RackEndpoint\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}